[package]
name = "quantumsim-py"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PyO3 bindings for quantumsim-core"

[lib]
name = "_quantumsim"
crate-type = ["cdylib"]

[dependencies]
quantumsim-core = { path = "../quantumsim-core" }
pyo3 = { version = "0.22", features = ["extension-module"] }
