[package]
name = "negforge-py"
version.workspace = true
edition.workspace = true
license.workspace = true
description = "PyO3 bindings for negforge-core"

[lib]
name = "_negforge"
crate-type = ["cdylib"]

[dependencies]
negforge-core = { path = "../negforge-core" }
pyo3 = { version = "0.22", features = ["extension-module"] }
